//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public string TotalArea { get; set; }
        public string Rooms { get; set; }
        public string Floor { get; set; }
        public int id { get; set; }
    
        public virtual RealEstate RealEstate { get; set; }
    }
}
