//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseFilter
    {
        public string MinFloors { get; set; }
        public string MaxFloors { get; set; }
        public string MinArea { get; set; }
        public string MaxArea { get; set; }
        public string MinRooms { get; set; }
        public string MaxRooms { get; set; }
        public int id { get; set; }
    
        public virtual RealEstateFilter RealEstateFilter { get; set; }
    }
}
