//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        public int id { get; set; }
        public string Address { get; set; }
        public string Coordinate { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual House House { get; set; }
        public virtual Land Land { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
