//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateFilter
    {
        public int id { get; set; }
    
        public virtual ApartmentFilter ApartmentFilter { get; set; }
        public virtual Demand Demand { get; set; }
        public virtual HouseFilter HouseFilter { get; set; }
        public virtual LandFilter LandFilter { get; set; }
    }
}
